# Paths and alpha for sampling dev set
alpha: 0.2
output_length: 100000
combined_data_output: data/multilingual/uralic_mrl_dev_alpha02.txt
data_files:
    russian:
        directory: data/indo-european/russian
        files: [ru_oscar_cleaned_dev.txt]
    hungarian:
        directory: data/uralic/hungarian
        files: [hu_oscar_cleaned_dev.txt]
    finnish:
        directory: data/uralic/finnish
        files: [fi_oscar_cleaned_dev.txt]
    estonian:
        directory: data/uralic/estonian
        files: [et_oscar_cleaned_dev.txt]
    erzya:
        directory: data/uralic/erzya
        files: [myv_combined_cleaned_dev.txt]
    sami:
        directory: data/uralic/sami
        files: [sami_combined_cleaned_dev.txt]
    
    
    

